### ISSUE TITLE
Method-creator function runs too frequently

### ISSUE THREAD

**Issue by deanius** [pelotom/use-methods#14]
The function from a state to the methods, what I call the method factory, is it supposed to run as often as it does in this CodeSanbox: https://codesandbox.io/s/proud-bird-izc85? It might be of no consequence but I just thought I’d check.

**Comment by pelotom** [comment]
Currently we rerun the the `methods` factory function on each state change to obtain the set of methods, since the set of methods could dynamically change in response to the state changing:

https://github.com/pelotom/use-methods/blob/43382d4281b0c46a0deaa15910bd3866c45882e0/src/index.ts#L51

But this is admittedly pretty silly, and in fact I don't think it would even work if you tried to change the set of methods, because the method names (aka action types) are used as hook dependencies:

https://github.com/pelotom/use-methods/blob/43382d4281b0c46a0deaa15910bd3866c45882e0/src/index.ts#L61

which must be of constant length. So I think we should make it a requirement that the set of method names remains constant, in which case we can memoize `actionTypes`, and then you won't see these extra invocations.

**Comment by deanius** [comment]
That's an interesting implication with hooks - do you have any further explanation of 'must be of constant length' - is that a rule of hooks?

It sounds like memoizing would be good.

I'm looking for a place to grab a reference to those methods, so I can invoke them from certain event handlers - so I want them to be stable. If they're already said to be stable, I think the extra invocations wouldn't add much.

PS Re github line/commit references - how did you embed those references?

**Comment by pelotom** [comment]
> That's an interesting implication with hooks - do you have any further explanation of 'must be of constant length' - is that a rule of hooks?

Yes, it's a rule of hooks. If your deps array changes length you'll get a warning like this:

```
Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant.
```

> I'm looking for a place to grab a reference to those methods, so I can invoke them from certain event handlers - so I want them to be stable. If they're already said to be stable, I think the extra invocations wouldn't add much.

I'm not sure what you mean by this exactly, but the `callbacks` that comes back in `const [state, callbacks] = useMethods(...)` is stable. The extra invocation of the `methods` factory function is only used to determine the set of method _names_, but since they shouldn't change this should only have to be done once.

> PS Re github line/commit references - how did you embed those references?

Copy a permalink to a line number from the source view:

![image](https://user-images.githubusercontent.com/128019/58566719-f639fc80-81e5-11e9-989b-85b3a915b7ab.png)

and just paste it into your comment.

**Comment by deanius** [comment]
Thank you!
